Fix exception on external URL documents
The Wagtail view requires access to a file object, so we add a default
to use when the external urls are provided

ValueError: The 'file' attribute has no file associated with it.